### ISSUE TITLE
scripts to build sim-recon on pull request

### ISSUE THREAD

**Issue by markito3** [JeffersonLab/build_scripts#5]
Created a new branch of build scripts, "pull_request", with two new scripts: "build_pull_request.sh" and "build_pull_request_report.sh". The former takes a branch name as input (specified on the command line) and does the build. The latter does a grep of a log file (specified on the command line) to pull out errors and warnings a la the nightly build.

https://github.com/JeffersonLab/build_scripts/tree/pull_request

**Comment by sdobbs** [comment]
@markito3:  This looks pretty good, but in principle, we can have multiple pull requests open at once, or in rapid succession, so I think each test build should be done in a separate directory, maybe distinguished by the git branch.

**Comment by markito3** [comment]
That feature is already built in as currently written. The "dirtag" thing gives the clone a non-standard directory name at clone time.

**Comment by sdobbs** [comment]
Sounds good!  Let's give this a shot!

**Comment by NathanSparks** [comment]
It would be better to test the merge of the PR-branch with master. Sometimes the PR-branch can get out of sync.

Where do you guys see the run-time tests coming in? I think it would be a good idea to run these tests (hdgeant/hd_root) after each PR-test build.

**Comment by sdobbs** [comment]
Well, the point of these tests is to check the branch before it's merged - I'm not aware of any way to check this without actually doing the merge.  To some extent, it's the responsibility of the developer to keep their branch up-to-date so that it can be merged without problems.

I am currently thinking that it would be useful to do some very small scale run-time tests when testing the pull request, but that a more serious test, with plots, profiling, archived results, etc. should be done on a regular basis, i.e. once or more a week.  Though my mind is still open.

@markito3, a couple requests:  Could build_pull_request.sh also print out or otherwise report the full path of the build log and maybe the exit code of the make command?

As a reminder, we were discussing having comments left with a format similar to the following:

===========================

Build status for this pull request: SUCCESS/FAILURE  [color coded]

Build log: [link]
Build errors: [link]
Build warnings: [link]
Location of build: [directory on scratch disk]

SUMMARY OF ERRORS:

[list]

==============================

**Comment by NathanSparks** [comment]
The merge would be done (before testing) in the local repository, not the remote. This way any potential merge issues can be caught as well. Of course, everyone should be encouraged to keep their branches up to date with master, but there will be situations when the PR-branch gets out of sync with master; The test is not very useful if it gives a different result than it would after the merge.

Small-scale (short running time) run-time tests are fine with me. Let's just try and make them useful.

**Comment by sdobbs** [comment]
Ah, OK.  The code snippet that I think @markito3 is working off of just checks out the particular branch we are interested in.  I could see an additional script also doing a merge test like you suggest.

**Comment by markito3** [comment]
A local merge is not a bad idea. If the merge fails however, the test is over with. At least the automatic part is over with. But that won't happen too often.

But guys, one thing at a time. Can we get this simple thing working first and then discuss the niceties?

**Comment by NathanSparks** [comment]
To merge with master, you could use the following code in the Makefile:
```
git clone -b $(SIM_RECON_BRANCH) $(SIM_RECON_URL) $(SIM_RECON_DIR)
cd $(SIM_RECON_DIR)
git merge origin/master
```
I am fine with proceeding with what we have for now, and adding the merge part later.

**Comment by sdobbs** [comment]
Point taken.  I am mostly dealing with some unexpected issues regarding the authentication from GitHub.  FWIW, I'm having an awfully tough time connecting from off-site today...

**Comment by sdobbs** [comment]
I think we can close this by now... =)
